name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-14, ubuntu-22.04]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: AlchemyViewer/action-autobuild@v4
        with:
          addrsize: ${{ matrix.addrsize }}
          build-variables-repo: alchemyviewer/build-variables
          build-variables-ref: alchemy
          setup-macos-codesign: true
          macos-p12-base64: ${{ secrets.APPLE_CERT_BASE64 }}
          macos-p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}
          macos-p12-id: ${{ secrets.APPLE_CERT_ID }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: alchemyviewer/action-autobuild-release@v4
        with:
          public: true
